### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by LanesGood** [developmentseed/observe-dashboard#10]
TBD if needed. Potential ideas for features:
- latest photos
- latest traces
- global map of **↑**
- top contributing users
- splash content for advertising the Observe mobile app with download links

With this in mind, I'm thinking that an enhanced version of the Observe API dashboard could function as the desktop home for Observe. Non logged-in users would be able to see the content above. Logged in users would also have the navigation links for the traces, photos, and users tables.

**Comment by LanesGood** [comment]
Two mockups showing options for a logged out landing page, and one option for a logged in page:

Landing logged in:
![Landing-loggedin](https://user-images.githubusercontent.com/12634024/69375349-1ff44d80-0c76-11ea-8eea-ded7570fb103.png)

Landing logged out dark:
![Landing-loggedout-dark](https://user-images.githubusercontent.com/12634024/69375350-1ff44d80-0c76-11ea-94bf-2c34ebb23063.png)

Landing logged out light:
![Landing-loggedout-light](https://user-images.githubusercontent.com/12634024/69375351-1ff44d80-0c76-11ea-9fd6-906609b6f24b.png)

**Comment by LanesGood** [comment]
@vgeorge images for background, separated
[Observe-dashboard-landing-bg.zip](https://github.com/developmentseed/observe-dashboard/files/3941202/Observe-dashboard-landing-bg.zip)

**Comment by vgeorge** [comment]
Opened a issue for a future dev cycle for the logged landing page (https://github.com/developmentseed/observe-dashboard/issues/5). I wanted keep tracking the unlogged page, which was already implemented, on [milestone 1](https://github.com/developmentseed/observe-dashboard/milestone/1)
