### ISSUE TITLE
Add pagination

### ISSUE THREAD

**Issue by vgeorge** [developmentseed/observe-dashboard#18]
The pagination component at the wireframe:

![Screenshot 2019-11-05 11 30 50](https://user-images.githubusercontent.com/329694/68204383-bf9bb580-ffbf-11e9-92d3-c89ccd6ee4c8.png)

@LanesGood, I wanted to clarify some points before implementation:

- Should we include first/last page button, in addition to previous/next?
- Are we going to display page numbers or item count in pagination text?
- If we choose page numbers, I believe we need include total item count in the pagination component or somewhere else in the page.

**Comment by LanesGood** [comment]
@vgeorge as mentioned, I think that the pagination will end up being a "nice to have" given the flexibility of table sorting, filters and search. However, I think that your suggestions are on point with inclusion of more detail. 
- First/Last page button: yes
- Pagination text = item count

New mock (pagination moved to below table to avoid conflicting space concerns with filter toolbar):
![image](https://user-images.githubusercontent.com/12634024/68219817-a3dee200-ffb4-11e9-95a6-80050cde1931.png)

**Comment by vgeorge** [comment]
Implemented.
