### ISSUE TITLE
Table component w/ sortable columns

### ISSUE THREAD

**Issue by LanesGood** [developmentseed/observe-dashboard#20]
Table component should be rendered for the sandbox with sortable columns w/ ascending/descending icons. Configurable to turn sort on/off depending on column

![image](https://user-images.githubusercontent.com/12634024/68218857-00d99880-ffb3-11e9-9427-cfbcc17753bb.png)

Splitting all other table functions and actions into separate issues.

**Comment by vgeorge** [comment]
Implemented.
