### ISSUE TITLE
Table UI - Row actions

### ISSUE THREAD

**Issue by LanesGood** [developmentseed/observe-dashboard#24]
As a user, I can perform actions on individual traces or multiple traces from the photos/traces list page. These actions include:
- Delete (confirmation required)
- Export to JOSM
- Download
![image](https://user-images.githubusercontent.com/12634024/68219331-d20ff200-ffb3-11e9-8d47-e16a7e39e71d.png)

![image](https://user-images.githubusercontent.com/12634024/68219358-db00c380-ffb3-11e9-851f-56cfc84356b9.png)

**Comment by vgeorge** [comment]
Implemented.
