### ISSUE TITLE
Table UI - trace length filter

### ISSUE THREAD

**Issue by LanesGood** [developmentseed/observe-dashboard#25]
Length range slider to be connected to trace length date
![image](https://user-images.githubusercontent.com/12634024/68220126-2b2c5580-ffb5-11e9-90df-266376ff16d6.png)
- Using [`react-input-range`](https://www.npmjs.com/package/react-input-range) for this at the time being, but feel free to suggest other options

**Comment by vgeorge** [comment]
Implemented. We chose to use input boxes instead of sliders to avoid performing an additional query to get the max value.
