### ISSUE TITLE
Round coordinates decimal places (and link?)

### ISSUE THREAD

**Issue by vgeorge** [developmentseed/observe-dashboard#29]
I believe its not necessary to display more than five decimal places for coordinates in the interface, as this precision is enough to differentiate places at street level.

@LanesGood do you think we should add links to OpenStreetMap in coordinate pairs? No marker is added when linking via coordinates, but it might be helpful to check photo/image aproximate location. Example:

https://www.openstreetmap.org/#map=19/-23.58688/-46.65548

**Comment by LanesGood** [comment]
@vgeorge this is a great idea, and I think we should provide these links.

Will we eventually be adding an Observe Dashboard map? My only thought on linking the coordinate pairs is that we may eventually want to link to the internal dashboard map instead of OSM.

**Comment by vgeorge** [comment]
The coordinate issue was fixed. Opened an issue for the map feature: https://github.com/developmentseed/observe-dashboard/issues/53
