### ISSUE TITLE
Photo management

### ISSUE THREAD

**Issue by vgeorge** [developmentseed/observe-dashboard#3]
Opening this to start documenting features expected at the dashboard in relation to photos: 

- Browse photos in a list
- Browse photos in a map (?)
- Filters by: user, date range, bounding box (?)
- View photo
- Download photo
- Update photo meta
- Remove photo
- Adding osm object to photo
- Remove osm object from photo

Please let me know you comments.

**Comment by LanesGood** [comment]
Does there need to be any validation process for the association of osm data with a photo? 

Additionally, can anyone update the meta of any photo?

**Comment by vgeorge** [comment]
I would keep editing restricted to `label/description` field and OSM objects.

**Comment by vgeorge** [comment]
I believe there is no further action here, listed features have their own tickets.
