### ISSUE TITLE
Open photo directly in JOSM

### ISSUE THREAD

**Issue by LanesGood** [developmentseed/observe-dashboard#36]
Per conversations with users, we've received the request to add the "Export to JOSM" button to the photo page. The use case here being that if a user wants to refer to photo details to update a feature (ex: number of floors in a building), and have JOSM's photo plugin, they can skip the step of downloading a photo and opening it in a separate application, or then dragging to JOSM.

**Comment by vgeorge** [comment]
Looking at [JOSM docs](https://josm.openstreetmap.de/wiki/Help/RemoteControlCommands) it doesn't seem Remote Control has support to open geotagged photos. I've tried to pass a [geotagged image](https://www.geoimgr.com/images/samples/england-london-bridge.jpg), it just returns "OK" but nothing is added. Example URL:

http://localhost:8111/import?url=https://www.geoimgr.com/images/samples/england-london-bridge.jpg
