### ISSUE TITLE
Traces management

### ISSUE THREAD

**Issue by vgeorge** [developmentseed/observe-dashboard#4]
Opening this to start documenting features expected at the dashboard in relation to traces:

- Browse traces in a list
- Browse traces in a map (?)
- Filters by: user, date range, bounding box (?)
- View trace
- Download trace
- Update trace meta
- Remove trace
- Open trace in JOSM #2

Please let me know your comments.

**Comment by LanesGood** [comment]
Can anyone update the meta of any trace? Relates to #6

(Same comment in #3)

**Comment by vgeorge** [comment]
I believe there is no further action here, listed features have their own tickets.
