### ISSUE TITLE
Reloading a deleted trace page breaks

### ISSUE THREAD

**Issue by geohacker** [developmentseed/observe-dashboard#43]
![image](https://user-images.githubusercontent.com/371666/69802947-c4d7d300-1200-11ea-9eea-5d96a3754484.png)

### Steps to reproduce
* Open a trace in a new tab
* Delete the trace from the main page or using the phone
* Reload the trace page. 

### Expected
* Should redirect to the index page or say the trace is not found?

cc @vgeorge

**Comment by vgeorge** [comment]
Fixed. You can test by accessing this link:

http://observe-dev.surge.sh/traces/5YBHUHIYXDHBTJ1
