### ISSUE TITLE
base path that is used by asset & navigation links

### ISSUE THREAD

**Issue by sethvincent** [developmentseed/observe-dashboard#47]
The dashboard needs to support deploying at a pathname such as `example.com/observe`

In scoreboard there is an APP_URL_PREFIX env var that can be set to the pathname that the app is deployed on, and then any links use that prefix through a wrapper function around Next.js's link/router functionality.

We could do something similar in this project.

@developmentseed/observe

**Comment by vgeorge** [comment]
Implemented. Please reopen if any issue surfaces.
