### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by vgeorge** [developmentseed/observe-dashboard#5]
Opening this to start documenting features expected at the dashboard in relation to users:

- User index
- Search by name
- View user (list traces, photos) #7
- Update user 
- Promote/demote user #6

Please let me know your comments.

**Comment by LanesGood** [comment]
@vgeorge thanks for this and the other lists in the feature tickets - this is very helpful for thinking through UI/UX. 

Does "View User" also imply that a user has an individual profile/dashboard page? If a user has many traces and photos I can imagine that a user table with these items would quickly become overpopulated. I don't know if there is a strong use case for this, but a user profile could also provide a unique id for linking.

I think that user roles would also be useful to ensure that only people with appropriate privileges can delete and modify certain items. I'll add this as a separate feature

**Comment by vgeorge** [comment]
@LanesGood Apologies for the delay on this. I saw that you create an issue for the user page, I agree that a separate view is needed for that. I've added issue links above for better tracking.

**Comment by vgeorge** [comment]
Related issues:

- Individual page #7 
- User Roles #6
- User list page #30

I believe there is no further action here, let follow up on specific issues.
