### ISSUE TITLE
User Roles

### ISSUE THREAD

**Issue by LanesGood** [developmentseed/observe-dashboard#6]
One feature to add across the whole application would be user roles such as "Admin" and "Mapper." There could be more. 

**Admins** would be able to access all features, including deletion of traces and photos, and the user management update/promote features.

**Mappers** should _not_ be able to:
- remove photos or traces other than their own
- edit photo or trace meta unrestricted - they should have to "suggest" or "request" changes
- promote/demote other users

**Comment by vgeorge** [comment]
Implemented.
